Repository 47ng/nuqs, pull requests merged in 2024-12, with the labels that each got.

#789 doc: Add Liminity.se as sponsor 💖
  packages/docs/src/app/(pages)/_landing/dependents.tsx
Labels: documentation

#797 chore: Run GHA on Ubuntu 24.04
  .github/workflows/analyse-nextjs-release.yml
  .github/workflows/ci-cd.yml
  .github/workflows/milestone-automation.yml
  .github/workflows/pkg.pr.new.yml
  .github/workflows/pr-base-enforcement.yml
  .github/workflows/ship-it.yml
  .github/workflows/snapshot-release.yml
  .github/workflows/test-against-nextjs-release.yml
Labels: deploy:preview

#795 docs: Document testing nuqs based hooks
  packages/docs/content/docs/testing.mdx
Labels: documentation

#819 chore: Enable provenance
  .github/workflows/ci-cd.yml
  .github/workflows/snapshot-release.yml
  packages/nuqs/package.json
Labels: internal

#821 fix: Support `?` characters in serializer base
  packages/nuqs/src/serializer.test.ts
  packages/nuqs/src/serializer.ts
Labels: feature/serializer

#834 chore: Reduce the amount of Slack notifications
  .github/workflows/ci-cd.yml
Labels: internal
