Repository 47ng/nuqs, pull requests merged in 2025-07, with the labels that each got.

#1025 docs: Extend next-app example to include more features
  packages/examples/next-app/src/app/_components/client.tsx
  packages/examples/next-app/src/app/_components/filter.tsx
  packages/examples/next-app/src/app/_components/pagination.tsx
  packages/examples/next-app/src/app/_components/server.tsx
  packages/examples/next-app/src/app/_components/users-list.tsx
  packages/examples/next-app/src/app/page.tsx
  packages/examples/next-app/src/app/searchParams.tsx
  packages/examples/next-app/src/data.ts
Labels: examples

#1037 doc: Add Aurora Scharff as a sponsor 💖
  packages/docs/src/app/(pages)/_landing/quotes/quotes-section.tsx
  packages/docs/src/app/(pages)/_landing/sponsors.tsx
Labels: documentation

#1041 doc: Fix transition docs to not call parser as function
  README.md
  packages/docs/content/docs/options.mdx
Labels: documentation

#1038 feat(types): Add `const` modifier to literal parsers to auto-infer their arguments as literals
  README.md
  packages/docs/content/docs/options.mdx
  packages/docs/content/docs/parsers/built-in.mdx
  packages/docs/content/docs/parsers/demos.tsx
  packages/docs/content/docs/testing.mdx
  packages/docs/content/docs/utilities.mdx
  packages/docs/src/app/globals.css
  packages/e2e/shared/specs/render-count.params.ts
  packages/e2e/shared/specs/stitching.defs.ts
  packages/nuqs/src/parsers.test.ts
  packages/nuqs/src/parsers.ts
  packages/nuqs/tests/parsers.test-d.ts
Labels: deploy:preview, parsers/built-in

#1043 doc: Title is hidden behind headers on mobile
  packages/docs/src/app/globals.css
Labels: documentation

#1051 doc: add effect schema parser page
  packages/docs/content/docs/parsers/community/effect-schema-demo.tsx
  packages/docs/content/docs/parsers/community/effect-schema.mdx
  packages/docs/content/docs/parsers/community/meta.json
  packages/docs/package.json
  pnpm-lock.yaml
Labels: documentation, parsers/community

#1052 doc: Debounce docs edits
  packages/docs/content/docs/options.mdx
Labels: documentation
