Repository 47ng/nuqs, pull requests merged in 2025-02, with the labels that each got.

#894 chore: Update deps
  package.json
  packages/docs/package.json
  packages/e2e/next/package.json
  packages/e2e/react-router/v6/package.json
  packages/e2e/react-router/v7/package.json
  packages/e2e/react/package.json
  packages/e2e/remix/package.json
  packages/e2e/shared/package.json
  packages/nuqs/package.json
  packages/scripts/package.json
  pnpm-lock.yaml
Labels: dependencies

#892 chore: Create CODE_OF_CONDUCT.md
  CODE_OF_CONDUCT.md
Labels: internal

#791 feat: Add `parseAsPageIndex` parser
  packages/docs/content/docs/parsers/built-in.mdx
  packages/docs/content/docs/parsers/community/tanstack-table.generator.tsx
  packages/docs/content/docs/parsers/demos.tsx
  packages/e2e/next/cypress/e2e/cache.cy.js
  packages/e2e/next/cypress/e2e/useQueryState.cy.js
  packages/e2e/next/cypress/e2e/useQueryStates.cy.js
  packages/e2e/next/src/app/app/cache/all.tsx
  packages/e2e/next/src/app/app/cache/get.tsx
  packages/e2e/next/src/app/app/cache/page.tsx
  packages/e2e/next/src/app/app/cache/searchParams.ts
  packages/e2e/next/src/app/app/cache/set.tsx
  packages/e2e/next/src/app/app/useQueryState/page.tsx
  packages/e2e/next/src/app/app/useQueryStates/page.tsx
  packages/e2e/next/src/pages/pages/useQueryState/index.tsx
  packages/e2e/next/src/pages/pages/useQueryStates/index.tsx
  packages/nuqs/src/parsers.test.ts
  packages/nuqs/src/parsers.ts
Labels: feature, parsers/built-in

#908 fix: useQueryStates does not update values correctly when config changes
  packages/docs/src/app/playground/_demos/repro-907/page.tsx
  packages/nuqs/src/useQueryStates.test.ts
  packages/nuqs/src/useQueryStates.ts
Labels: feature/useQueryStates

#911 feat: Add scroll option support for React SPA adapter
  packages/e2e/next/cypress/e2e/shared/scroll.cy.ts
  packages/e2e/next/src/app/app/(shared)/scroll/page.tsx
  packages/e2e/next/src/pages/pages/scroll.tsx
  packages/e2e/react-router/v6/cypress/e2e/shared/scroll.cy.ts
  packages/e2e/react-router/v6/src/react-router.tsx
  packages/e2e/react-router/v6/src/routes/scroll.tsx
  packages/e2e/react-router/v7/app/routes.ts
  packages/e2e/react-router/v7/app/routes/scroll.tsx
  packages/e2e/react-router/v7/cypress/e2e/shared/scroll.cy.ts
  packages/e2e/react/cypress/e2e/shared/scroll.cy.ts
  packages/e2e/react/src/routes.tsx
  packages/e2e/react/src/routes/scroll.tsx
  packages/e2e/remix/app/routes/scroll.tsx
  packages/e2e/remix/cypress/e2e/shared/scroll.cy.ts
  packages/e2e/shared/cypress.config.ts
  packages/e2e/shared/specs/scroll.cy.ts
  packages/e2e/shared/specs/scroll.tsx
  packages/nuqs/src/adapters/react.ts
Labels: adapters/react

#915 doc: Add Unkey as sponsor 💖
  packages/docs/src/app/(pages)/_landing/dependents.tsx
  packages/docs/src/app/(pages)/_landing/sponsors.tsx
  packages/docs/src/app/layout.tsx
Labels: documentation

#920 doc: Add OpenStatus as sponsor 💖
  packages/docs/src/app/(pages)/_landing/dependents.tsx
  packages/docs/src/app/(pages)/_landing/sponsors.tsx
Labels: documentation

#918 chore: Update pkg.pr.new comments
  .github/workflows/pkg.pr.new.yml
  packages/nuqs/remove-me
Labels: internal, deploy:preview

#891 feat: Full-page navigation option for `shallow: false` updates in React SPA
  .github/workflows/ci-cd.yml
  packages/docs/content/docs/adapters.mdx
  packages/e2e/react/src/main.tsx
  packages/e2e/react/vite.config.ts
  packages/nuqs/src/adapters/react.ts
  turbo.json
Labels: feature, adapters/react

#922 doc: Fix the parseAsIndex demo
  packages/docs/content/docs/parsers/built-in.mdx
  packages/docs/content/docs/parsers/demos.tsx
Labels: documentation

#923 fix: Import React.cache only when needed
  packages/nuqs/src/cache.ts
Labels: feature/cache

#926 doc: Update withDefault JSDocs
  packages/nuqs/src/parsers.ts
Labels: documentation
