Repository 47ng/nuqs, pull requests merged in 2025-09, with the labels that each got.

#1110 feat: Add processUrlSearchParams middleware as adapter prop
  packages/docs/content/docs/options.client.tsx
  packages/docs/content/docs/options.mdx
  packages/nuqs/src/adapters/lib/context.ts
  packages/nuqs/src/adapters/testing.ts
  packages/nuqs/src/lib/queues/throttle.test.ts
  packages/nuqs/src/lib/queues/throttle.ts
  packages/nuqs/src/useQueryStates.test.ts
  packages/nuqs/src/useQueryStates.ts
  turbo.json
Labels: feature, deploy:preview

#1115 feat: add processUrlSearchParams to createSerializer
  packages/docs/content/docs/utilities.mdx
  packages/nuqs/src/serializer.test.ts
  packages/nuqs/src/serializer.ts
Labels: documentation, deploy:preview, feature/serializer

#1097 doc: Add Zod codecs community parsers
  packages/docs/content/docs/parsers/community/meta.json
  packages/docs/content/docs/parsers/community/zod-codecs.demo.tsx
  packages/docs/content/docs/parsers/community/zod-codecs.lib.ts
  packages/docs/content/docs/parsers/community/zod-codecs.mdx
  packages/docs/content/docs/parsers/community/zod-codecs.skeleton.tsx
  packages/docs/content/docs/parsers/community/zod-codecs.source.tsx
  packages/docs/package.json
  packages/docs/src/app/(pages)/stats/lib/npm.ts
  packages/docs/src/components/ui/input.tsx
  packages/nuqs/package.json
  packages/scripts/package.json
  pnpm-lock.yaml
Labels: documentation

#1121 chore: Prevent parallel runs of pkg.pr.new within a PR
  .github/workflows/pkg.pr.new.yml
Labels: internal

#1120 doc: Move to nuqs.dev
  .github/workflows/ci-cd.yml
  .github/workflows/test-against-nextjs-release.yml
  CONTRIBUTING.md
  README.md
  errors/NUQS-101.md
  errors/NUQS-303.md
  errors/NUQS-404.md
  errors/NUQS-414.md
  errors/NUQS-422.md
  packages/docs/content/blog/nuqs-2.5.mdx
  packages/docs/next.config.mjs
  packages/docs/src/app/(pages)/_landing/page-footer.tsx
  packages/docs/src/app/(pages)/blog/[slug]/page.tsx
  packages/docs/src/app/(pages)/blog/rss.xml/route.ts
  packages/docs/src/app/(pages)/page.tsx
  packages/docs/src/app/(pages)/react-paris/page.tsx
  packages/nuqs/package.json
  packages/nuqs/src/lib/errors.ts
  packages/nuqs/src/lib/queues/throttle.test.ts
Labels: documentation

#1123 doc: Add sitemap
  packages/docs/src/app/docs/[[...slug]]/page.tsx
  packages/docs/src/app/robots.ts
  packages/docs/src/app/sitemap.ts
  packages/docs/src/lib/url.ts
Labels: documentation

#1136 chore: split size-limit script from build process
  packages/nuqs/package.json
  turbo.json
Labels: internal

#1133 feat: add memory option in the testing adapter
  packages/docs/content/docs/testing.mdx
  packages/nuqs/src/adapters/testing.ts
  packages/nuqs/src/useQueryState.test.tsx
  packages/nuqs/src/useQueryStates.test.tsx
  packages/nuqs/tests/components/repro-1099.tsx
Labels: adapters/testing

#1134 feat: multi-parsers
  packages/docs/content/docs/parsers/built-in.mdx
  packages/docs/content/docs/parsers/demos.tsx
  packages/docs/content/docs/parsers/making-your-own.mdx
  packages/docs/src/app/styles/tweaks.css
  packages/docs/src/components/querystring.tsx
  packages/e2e/next/src/app/app/(shared)/native-array/page.tsx
  packages/e2e/next/src/pages/pages/native-array.tsx
  packages/e2e/react-router/v6/src/react-router.tsx
  packages/e2e/react-router/v6/src/routes/native-array.tsx
  packages/e2e/react-router/v7/app/routes.ts
  packages/e2e/react-router/v7/app/routes/native-array.tsx
  packages/e2e/react/src/routes.tsx
  packages/e2e/react/src/routes/native-array.tsx
  packages/e2e/remix/app/routes/native-array.tsx
  packages/e2e/shared/shared.cy.ts
  packages/e2e/shared/specs/native-array.cy.ts
  packages/e2e/shared/specs/native-array.tsx
  packages/e2e/tanstack-router/cypress/e2e/shared/native-array.cy.ts
  packages/e2e/tanstack-router/src/routes/native-array.tsx
  packages/nuqs/package.json
  packages/nuqs/src/adapters/lib/key-isolation.ts
  packages/nuqs/src/api.test.ts
  packages/nuqs/src/lib/compare.test.ts
  packages/nuqs/src/lib/compare.ts
  packages/nuqs/src/lib/queues/debounce.ts
  packages/nuqs/src/lib/queues/throttle.ts
  packages/nuqs/src/lib/safe-parse.ts
  packages/nuqs/src/lib/search-params.ts
  packages/nuqs/src/lib/sync.ts
  packages/nuqs/src/loader.test.ts
  packages/nuqs/src/loader.ts
  packages/nuqs/src/parsers.test.ts
  packages/nuqs/src/parsers.ts
  packages/nuqs/src/serializer.test.ts
  packages/nuqs/src/serializer.ts
  packages/nuqs/src/testing.ts
  packages/nuqs/src/useQueryState.test.tsx
  packages/nuqs/src/useQueryState.ts
  packages/nuqs/src/useQueryStates.test.tsx
  packages/nuqs/src/useQueryStates.ts
Labels: parsers/built-in
