Repository 47ng/nuqs, pull requests merged in 2025-08, with the labels that each got.

#996 fix: Replace require by default conditional export field
  errors/NUQS-101.md
  packages/nuqs/esm-only.cjs
  packages/nuqs/package.json
Labels: deploy:preview

#1065 chore: Add TanStack Router to og:images
  packages/docs/public/og/adapters.jpg
  packages/docs/src/app/opengraph-image.jpg
  packages/docs/src/app/twitter-image.jpg
Labels: documentation

#1067 chore: Improve stats page
  packages/docs/src/app/(pages)/stats/_components/downloads.client.tsx
  packages/docs/src/app/(pages)/stats/_components/downloads.tsx
  packages/docs/src/app/(pages)/stats/_components/versions.tsx
  packages/docs/src/app/(pages)/stats/lib/versions.ts
Labels: documentation, internal

#1070 doc: prevent NaN appearing in pagination example
  packages/docs/src/app/playground/(demos)/pagination/rendering-controls.tsx
Labels: documentation

#1080 chore: Pass children as config in createElement to avoid ts-expect-error
  packages/nuqs/src/adapters/next/app.ts
  packages/nuqs/src/adapters/react.ts
Labels: adapters/next/app, internal, adapters/react

#1081 chore: Reduce the bundle size
  packages/e2e/shared/specs/stitching.tsx
  packages/nuqs/package.json
  packages/nuqs/src/adapters/lib/patch-history.ts
  packages/nuqs/src/adapters/lib/react-router.ts
  packages/nuqs/src/adapters/react.ts
  packages/nuqs/src/lib/compose.ts
  packages/nuqs/src/lib/debug.ts
  packages/nuqs/src/lib/emitter.test.ts
  packages/nuqs/src/lib/emitter.ts
  packages/nuqs/src/lib/queues/debounce.ts
  packages/nuqs/src/lib/queues/throttle.ts
  packages/nuqs/src/lib/queues/useSyncExternalStores.test.ts
  packages/nuqs/src/lib/sync.ts
  packages/nuqs/src/lib/with-resolvers.ts
  packages/nuqs/src/loader.ts
  packages/nuqs/src/parsers.ts
  packages/nuqs/src/useQueryState.ts
  pnpm-lock.yaml
Labels: dependencies, internal, feature/useQueryState

#1082 doc: Add nuqs 2.5 release blog post
  packages/docs/content/blog/nuqs-2.5-key-isolation.client.tsx
  packages/docs/content/blog/nuqs-2.5.mdx
  packages/docs/content/blog/nuqs-2.5.og.png
  packages/docs/src/app/(pages)/_landing/sponsors.tsx
  packages/docs/src/app/styles/tweaks.css
  packages/docs/src/components/ui/pr-line.tsx
  packages/docs/src/components/vercel-oss-badge.tsx
Labels: documentation

#1093 doc: Add feature support component
  packages/docs/content/docs/adapters.mdx
  packages/docs/content/docs/batching.mdx
  packages/docs/content/docs/internal/design-system.mdx
  packages/docs/content/docs/options.mdx
  packages/docs/content/docs/parsers/built-in.mdx
  packages/docs/content/docs/server-side.mdx
  packages/docs/content/docs/testing.mdx
  packages/docs/content/docs/utilities.mdx
  packages/docs/mdx-components.tsx
  packages/docs/package.json
  packages/docs/src/app/(pages)/_landing/works-with.tsx
  packages/docs/src/components/feature-support-matrix.tsx
  packages/docs/src/components/frameworks.tsx
  packages/docs/src/components/ui/popover.tsx
  packages/docs/src/components/ui/tooltip-popover.tsx
  packages/docs/src/components/ui/tooltip.tsx
  pnpm-lock.yaml
Labels: documentation

#1088 doc: Move stats charts from Tremor to EvilCharts
  packages/docs/package.json
  packages/docs/src/app/(pages)/stats/_components/downloads.client.tsx
  packages/docs/src/app/(pages)/stats/_components/downloads.tsx
  packages/docs/src/app/(pages)/stats/_components/graph.skeleton.tsx
  packages/docs/src/app/(pages)/stats/_components/partial-line-chart.tsx
  packages/docs/src/app/(pages)/stats/_components/stars.client.tsx
  packages/docs/src/app/(pages)/stats/_components/stars.gazers-list.tsx
  packages/docs/src/app/(pages)/stats/_components/stars.tsx
  packages/docs/src/app/(pages)/stats/_components/svg-curve-graph.tsx
  packages/docs/src/app/(pages)/stats/_components/test.tsx
  packages/docs/src/app/(pages)/stats/_components/tremor.ts
  packages/docs/src/app/(pages)/stats/_components/versions.tsx
  packages/docs/src/app/(pages)/stats/_components/widget.skeleton.tsx
  packages/docs/src/app/(pages)/stats/_components/widget.tsx
  packages/docs/src/app/(pages)/stats/lib/format.ts
  packages/docs/src/app/(pages)/stats/lib/github.ts
  packages/docs/src/app/(pages)/stats/lib/npm.ts
  packages/docs/src/app/(pages)/stats/lib/versions.ts
  packages/docs/src/app/(pages)/stats/page.tsx
  packages/docs/src/app/globals.css
  packages/docs/src/components/countdown.tsx
  packages/docs/src/components/logo.tsx
  packages/docs/src/components/ui/card.tsx
  packages/docs/src/components/ui/chart.tsx
  packages/docs/src/components/ui/tabs.tsx
  pnpm-lock.yaml
Labels: documentation

#1101 fix: Referential stability for the testing adapter
  packages/nuqs/src/adapters/testing.ts
  packages/nuqs/src/useQueryState.test.ts
  packages/nuqs/src/useQueryStates.test.ts
Labels: adapters/testing

#1103 doc: Fix all-time stats skeletons
  packages/docs/src/app/(pages)/stats/_components/downloads.tsx
  packages/docs/src/app/(pages)/stats/page.tsx
Labels: documentation

#1105 chore: Securing workflows
  .github/workflows/analyse-nextjs-release.yml
  .github/workflows/milestone-automation.yml
  .github/workflows/pkg.pr.new.yml
  .github/workflows/pr-base-enforcement.yml
  .github/workflows/pr-lint.yml
  .github/workflows/ship-it.yml
  .github/workflows/snapshot-release.yml
  .github/workflows/test-against-nextjs-release.yml
Labels: internal

#1108 chore: Use semantic-release/github 11.0.5 to handle deprecated search endpoints
  package.json
  pnpm-lock.yaml
Labels: internal
